-- Basic
require("core.autocmd")
require("core.plugins")
require("core.neoformat")
require("core.mappings")
require("core.colors")
require("core.configs")

-- Plugins
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.mason")
require("plugins.mason_nvim_dap")
require("plugins.telescope")
require("plugins.nullls")
require("plugins.autopairs")
require("plugins.comment")
require("plugins.autotag")
require("plugins.buffline")
require("plugins.dashboard")
require("plugins.hop")
require("plugins.lualine")
require("plugins.toggleterm")
require("plugins.whichkey")
require("plugins.poimandres")
require("plugins.surround")
require("plugins.symbols_outline")
require("plugins.transparent")
require("plugins.todo_comments")
