local wk = require("which-key")

wk.register({
  ["<leader>"] = {
    c = { name = "Comment", group = "Comment" },
    e = { desc = "File Manager" },
    f = { name = "Find", group = "Find" },
    g = { name = "Git", group = "Git" },
    h = { desc = "No highlight" },
    l = { name = "LSP", group = "LSP" },
    o = { desc = "Git status" },
    t = { name = "Terminal", group = "Terminal" },
    w = { desc = "Save" },
    x = { desc = "Close Buffer" },
  },
  ["<leader>cl"] = { desc = "Comment Line" },
  ["<leader>fb"] = { desc = "Find Buffer" },
  ["<leader>ff"] = { desc = "Find File" },
  ["<leader>fh"] = { desc = "Find Help" },
  ["<leader>fw"] = { desc = "Find Text" },
  ["<leader>gb"] = { desc = "Branches" },
  ["<leader>gc"] = { desc = "Commits" },
  ["<leader>gs"] = { desc = "Status" },
  ["<leader>lD"] = { desc = "Hover diagnostic" },
  ["<leader>la"] = { desc = "Action" },
  ["<leader>ld"] = { desc = "Diagnostic" },
  ["<leader>lf"] = { desc = "Format" },
  ["<leader>lr"] = { desc = "Rename" },
  ["<leader>ls"] = { desc = "Symbol" },
  ["<leader>tf"] = { desc = "Float terminal" },
  ["<leader>th"] = { desc = "Horizontal terminal" },
})
